CREATE TABLE IF NOT EXISTS `gw2_maps` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `map_id` smallint(4) unsigned NOT NULL DEFAULT '0',
  `continent_id` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `floor_id` smallint(3) NOT NULL DEFAULT '0',
  `region_id` smallint(3) NOT NULL DEFAULT '0',
  `default_floor` smallint(3) NOT NULL DEFAULT '0',
  `map_rect` tinytext COLLATE utf8mb4_bin NOT NULL,
  `continent_rect` tinytext COLLATE utf8mb4_bin NOT NULL,
  `min_level` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `max_level` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `name_de` tinytext COLLATE utf8mb4_bin NOT NULL,
  `name_en` tinytext COLLATE utf8mb4_bin NOT NULL,
  `name_es` tinytext COLLATE utf8mb4_bin NOT NULL,
  `name_fr` tinytext COLLATE utf8mb4_bin NOT NULL,
  `name_zh` tinytext COLLATE utf8mb4_bin NOT NULL,
  `data_de` text COLLATE utf8mb4_bin NOT NULL,
  `data_en` text COLLATE utf8mb4_bin NOT NULL,
  `data_es` text COLLATE utf8mb4_bin NOT NULL,
  `data_fr` text COLLATE utf8mb4_bin NOT NULL,
  `data_zh` text COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
