CREATE TABLE IF NOT EXISTS `gw2_skins` (
  `skin_id` int(6) unsigned NOT NULL,
  `signature` varchar(40) COLLATE utf8_bin NOT NULL,
  `file_id` int(10) NOT NULL DEFAULT '0',
  `type` tinytext COLLATE utf8_bin NOT NULL,
  `subtype` tinytext COLLATE utf8_bin NOT NULL,
  `properties` tinytext COLLATE utf8_bin NOT NULL,
  `name_de` tinytext COLLATE utf8_bin NOT NULL,
  `name_en` tinytext COLLATE utf8_bin NOT NULL,
  `name_es` tinytext COLLATE utf8_bin NOT NULL,
  `name_fr` tinytext COLLATE utf8_bin NOT NULL,
  `data_de` text COLLATE utf8_bin NOT NULL,
  `data_en` text COLLATE utf8_bin NOT NULL,
  `data_es` text COLLATE utf8_bin NOT NULL,
  `data_fr` text COLLATE utf8_bin NOT NULL,
  `updated` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `update_time` int(10) unsigned NOT NULL DEFAULT '0',
  `added` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`skin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;